openapi: 3.0.1
info:
  title: Star Wars
  description: implementing star wars api
  version: ''
servers:
  - url: https://ginsburgapim.azure-api.net/sw
paths:
  /people/:
    get:
      summary: Get People
      operationId: getpeople
      responses:
        '200':
          description: 
  '/people/{id}/':
    get:
      summary: GetPeopleById
      operationId: getpeoplebyid
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  /getfilm:
    get:
      summary: Get Film
      operationId: get-film
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/'
              example:
                count: 1
                films:
                  - title: A New Hope
                    release-date: '1977-05-25'
components:
  schemas:
    New Hope:
      type: object
      properties:
        count:
          type: integer
        films:
          type: array
          items:
            required:
              - title
              - release-date
            type: object
            properties:
              title:
                type: string
              release-date:
                type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]