apimServiceName: prod
namedValues:
loggers:
    - name: apiminsights
      properties:
        loggerType: applicationInsights
        description: prod application insights
        resourceId: "/subscriptions/c5797b67-98fc-4dfa-ae5a-2e7779a26e94/resourceGroups/APIMWorkshop/providers/microsoft.insights/components/apiminsights"
        credentials:
          instrumentationKey: "{{Logger-Credentials--63c9b73246346114e8da8df8}}"
        isBuffered: true
diagnostics:
   - name: apiminsights
     properties:
       verbosity: Error
       loggerId: "/subscriptions/c5797b67-98fc-4dfa-ae5a-2e7779a26e94/resourceGroups/APIMWorkshop/providers/Microsoft.ApiManagement/service/ginsburgapim-prod/loggers/apiminsights"
backends:
apis:
  - name: echo-api
    properties:
      serviceUrl: "http://someotherurl"