apimServiceName: prod
namedValues:
# loggers:
#     - name: apimdemoappinsights
#       properties:
#         loggerType: applicationInsights
#         description: prod application insights
#         resourceId: "/subscriptions/4400dccb-df1c-4421-91a3-d2cb708c2ee3/resourceGroups/APIMDemo/providers/microsoft.insights/components/apimdemoappinsights"
#         credentials:
#           instrumentationKey: "{{Logger-Credentials--66c490b9217d2019dc555c78}}"
#         isBuffered: true
# diagnostics:
#    - name: apimdemoappinsights
#      properties:
#        verbosity: Error
#        loggerId: "/subscriptions/4400dccb-df1c-4421-91a3-d2cb708c2ee3/resourceGroups/APIMDemo/providers/Microsoft.ApiManagement/service/apimdemoginsburgprod/loggers/apimdemoappinsights"
backends:
apis:
  - name: echo-api
    properties:
      serviceUrl: "http://someotherurl"