apimServiceName: prod
namedValues:
loggers:
    - name: apimdemoinsights
      properties:
        loggerType: applicationInsights
        description: prod application insights
        resourceId: "/subscriptions/4400dccb-df1c-4421-91a3-d2cb708c2ee3/resourceGroups/APIMDemo/providers/microsoft.insights/components/apimdemoappinsights"
        credentials:
          instrumentationKey: "{{Logger-Credentials--66c490b9217d2019dc555c77}}"
        isBuffered: true
diagnostics:
   - name: apimdemoinsights
     properties:
       verbosity: Error
       loggerId: "/subscriptions/4400dccb-df1c-4421-91a3-d2cb708c2ee3/resourceGroups/APIMDemo/providers/Microsoft.ApiManagement/service/apimdemoginsburgprod/loggers/apimdemoinsights"
ackends:
apis:
  - name: echo-api
    properties:
      serviceUrl: "http://someotherurl"